apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-application
  namespace: webgrip
  title: Backstage Application
  description: |
    The Backstage Application is the main application that serves the Backstage UI. It is a React application that is built with TypeScript.
  labels:
    tier: "2"
  links:
    - title: Website
      url: http://backstage.io
    - title: Documentation
      url: https://backstage.io/docs
    - title: Storybook
      url: https://backstage.io/storybook
    - title: Discord Chat
      url: https://discord.com/invite/EBHEGzX
    - title: Development URL
      url: https://backstage.test
      icon: dashboard
  tags:
    - backstage
  annotations:
    backstage.io/adr-location: docs/adr
    github.com/project-slug: webgrip/backstage-application
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: my-kubernetes-component
    backstage.io/code-coverage: enabled
    simpleicons.org/icon-slug: backstage
spec:
  type: service
  owner: group:webgrip/backstage
  lifecycle: experimental
  system: backstage-system
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: backstage-system
  namespace: webgrip
  title: Backstage
  description: |
    Backstage is an open-source developer portal that puts the developer experience first.
spec:
  owner: group:webgrip/backstage
  domain: webgrip/operations-domain
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: backstage-application-postgres
  namespace: webgrip
  title: Backstage Repository
  description: |
    The Postgres database for the Backstage application. It has pgvector and uuid-ossp extensions enabled.
  labels:
    tier: "2"
  annotations:
    github.com/project-slug: webgrip/backstage
    simpleicons.org/icon-slug: postgres
  tags:
    - backstage
spec:
  type: database
  owner: group:webgrip/backstage
  system: backstage-system
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Ryangr0
  namespace: default
  description: "Manual bridge user for Ryan"
spec:
  profile:
    displayName: Ryan Grippeling
    email: R.Grippeling@hotmail.com
  memberOf:
    - group:webgrip/application
    - group:webgrip/backstage
    - group:webgrip/c-level-group
    - group:webgrip/grafana
    - group:webgrip/infrastructure
